name: Build Vote

on:
  push:
    branches:
      - master
    paths:
      - "**"
  pull_request:
    branches:
      - master

jobs:
  build:
    uses: ybojko/voting-app-ci/.github/workflows/build.yml@master
    permissions:
      id-token: write
      contents: read
    with:
      service-name: vote
      context: .
      platforms: linux/amd64,linux/arm64,linux/arm/v7
    secrets:
      GIT_OPS_TOKEN: ${{ secrets.GIT_OPS_TOKEN }}
